### ISSUE TITLE
sass-rails 5.0.0 is out

### ISSUE THREAD

**Issue by swrobel** [vhyza/sass-rails-source-maps#16]
https://rubygems.org/gems/sass-rails

**Comment by bl4ckdu5t** [comment]
Has this been tested with 5.0.0. I use that with my web app and it isn't working. The only part of the docs I didn't follow was hitting the experiments tab in settings to enable sass debug which is because I can't find that tab even after enabling devtools experiments

**Comment by gkatsanos** [comment]
It's not working. No one knows anything about SASS and Rails. The devtools experiments thing is obsolete, this is part of the main settings since a year if not more. Desperation.

**Comment by vhyza** [comment]
This gem needs to be rewritten with new sass-rails 5.0. I haven't used Rails for quite a long time, so my motivation is not so strong. I'm planning to dive into this, but don't really know when I'll be able to. Anyway PR are welcome...

**Comment by gkatsanos** [comment]
@vhyza Can you give us some highlights on where to look for changes? Unless the new version of sass-rails is RADICALLy different it shouldn't be a pain.. We can look into this asap.

**Comment by vhyza** [comment]
@gkatsanos To be honest, I didn't take a look on new implementation of sass-rails, so I don't know what changed yet. Anyway this is small gem with just few files - https://github.com/vhyza/sass-rails-source-maps/tree/sass-rails-5.0.0.beta1/lib/sass-rails-source-maps ..

**Comment by gkatsanos** [comment]
It seems that Sprockets 4.0 will bring this out of the box.. but it wont be released till later this year.
my mind can't fit how a framework as sexy and hyped as rails doesn't do something as basic as source-mapping.

**Comment by vhyza** [comment]
Closed by 50aa40de688820c7784d65e0be1e53c39d6e3b8d.

**Comment by joshuapaling** [comment]
It would be great to add a note about it not working in the readme. I've been trying to get this working for a while, until I came across this issue and gave up.
