### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by gkatsanos** [vhyza/sass-rails-source-maps#18]

**Comment by vhyza** [comment]
It depends. Please, see first paragraph in README https://github.com/vhyza/sass-rails-source-maps#sass-rails-source-maps

**Comment by gkatsanos** [comment]
1 month of waiting and you answer to me with a paragraph that I've read and tried to implement about 15 times.

**Comment by vhyza** [comment]
Well, I answered this way for someone who eventually come across this issue (so not to close it without any answer). We discussed the situation in other issue (https://github.com/vhyza/sass-rails-source-maps/issues/16#issuecomment-75954397)..
